;this file for FamiTone2 library generated by text2data tool

headinthesand_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $30 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $b0 ;instrument $01
	.dw .env2,.env0,.env0
	.db $00
	.db $b0 ;instrument $02
	.dw .env2,.env0,.env0
	.db $00
	.db $b0 ;instrument $03
	.dw .env3,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $c6,$00,$00
.env2:
	.db $c3,$c0,$00,$01
.env3:
	.db $c8,$c6,$c5,$c4,$c3,$02,$c3,$00,$06


.song0ch0:
	.db $fb,$03
.song0ch0loop:
.ref0:
	.db $bf
.ref1:
	.db $bf
.ref2:
	.db $bf
.ref3:
	.db $bf
.ref4:
	.db $bf
.ref5:
	.db $bf
.ref6:
	.db $bf
.ref7:
	.db $bf
.ref8:
	.db $bf
.ref9:
	.db $bf
.ref10:
	.db $82,$4a,$00,$00,$00,$62,$00,$00,$00,$62,$00,$00,$00,$4a,$00,$00
	.db $00,$4a,$00,$00,$00,$58,$00,$00,$00,$58,$00,$00,$00,$4a,$00,$00
	.db $00
.ref11:
	.db $4a,$00,$00,$00,$62,$00,$00,$00,$62,$00,$00,$00,$4a,$00,$00,$00
	.db $4a,$00,$00,$00,$58,$00,$00,$00,$58,$00,$00,$00,$4a,$00,$00,$00
.ref12:
	.db $bf
.ref13:
	.db $bf
.ref14:
	.db $bf
.ref15:
	.db $bf
.ref16:
	.db $bf
.ref17:
	.db $bf
.ref18:
	.db $bf
.ref19:
	.db $bf
.ref20:
	.db $bf
.ref21:
	.db $bf
	.db $ff,$20
	.dw .ref11
	.db $ff,$20
	.dw .ref11
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref24:
	.db $bf
.ref25:
	.db $bf
.ref26:
	.db $bf
.ref27:
	.db $bf
.ref28:
	.db $bf
.ref29:
	.db $bf
.ref30:
	.db $bf
.ref31:
	.db $bf
.ref32:
	.db $bf
.ref33:
	.db $bf
.ref34:
	.db $bf
.ref35:
	.db $bf
.ref36:
	.db $8f,$86,$52,$85,$00,$85,$4a,$85,$00,$8d,$44,$85
.ref37:
	.db $4b,$01,$4b,$00,$89,$4a,$85,$00,$9d
.ref38:
	.db $8f,$52,$85,$00,$85,$4a,$85,$00,$8d,$44,$85
.ref39:
	.db $4b,$01,$4b,$00,$89,$46,$85,$00,$9d
.ref40:
	.db $8f,$44,$85,$00,$85,$4a,$85,$00,$85,$4e,$85,$00,$85
.ref41:
	.db $51,$01,$50,$85,$4f,$01,$4a,$85,$00,$85,$44,$85,$00,$85,$40,$85
.ref42:
	.db $00,$bd
.ref43:
	.db $bf
.ref44:
	.db $8f,$4e,$85,$00,$85,$40,$85,$00,$85,$44,$85,$4b,$00,$81
.ref45:
	.db $51,$01,$50,$85,$4f,$01,$4a,$85,$00,$85,$44,$85,$00,$85,$4a,$85
.ref46:
	.db $00,$bd
.ref47:
	.db $bf
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref48:
	.db $80,$32,$00,$00,$00,$32,$00,$00,$00,$3a,$00,$00,$00,$3a,$00,$00
	.db $00,$40,$00,$40,$00,$40,$00,$00,$00,$44,$00,$00,$00,$40,$00,$00
	.db $00
.ref49:
	.db $32,$00,$00,$00,$32,$00,$00,$00,$3a,$00,$00,$00,$3a,$00,$00,$00
	.db $40,$00,$40,$00,$40,$00,$00,$00,$44,$00,$00,$00,$40,$00,$00,$00
	.db $ff,$20
	.dw .ref49
	.db $ff,$20
	.dw .ref49
.ref52:
	.db $3c,$00,$00,$00,$3c,$00,$00,$00,$44,$00,$00,$00,$44,$00,$00,$00
	.db $4a,$00,$4a,$00,$4a,$00,$00,$00,$4e,$00,$00,$00,$4a,$00,$00,$00
	.db $ff,$20
	.dw .ref52
	.db $ff,$20
	.dw .ref49
	.db $ff,$20
	.dw .ref49
.ref56:
	.db $28,$00,$00,$00,$28,$00,$00,$00,$30,$00,$00,$00,$30,$00,$00,$00
	.db $36,$00,$36,$00,$36,$00,$00,$00,$3a,$00,$00,$00,$36,$00,$00,$00
.ref57:
	.db $24,$00,$00,$00,$24,$00,$00,$00,$2c,$00,$00,$00,$2c,$00,$00,$00
	.db $32,$00,$32,$00,$32,$00,$00,$00,$36,$00,$00,$00,$32,$00,$00,$00
.ref58:
	.db $32,$00,$bb
.ref59:
	.db $bf
	.db $ff,$20
	.dw .ref49
	.db $ff,$20
	.dw .ref49
	.db $ff,$20
	.dw .ref49
	.db $ff,$20
	.dw .ref49
	.db $ff,$20
	.dw .ref52
	.db $ff,$20
	.dw .ref52
	.db $ff,$20
	.dw .ref49
	.db $ff,$20
	.dw .ref49
	.db $ff,$20
	.dw .ref56
	.db $ff,$20
	.dw .ref57
.ref70:
	.db $32,$00,$bb
.ref71:
	.db $bf
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref72:
	.db $bf
.ref73:
	.db $bf
.ref74:
	.db $bf
.ref75:
	.db $bf
.ref76:
	.db $bf
.ref77:
	.db $bf
.ref78:
	.db $bf
.ref79:
	.db $bf
.ref80:
	.db $bf
.ref81:
	.db $bf
.ref82:
	.db $87,$84,$10,$85,$10,$85,$08,$85,$08,$85,$10,$85,$10,$85,$08,$85
.ref83:
	.db $08,$85,$10,$85,$10,$85,$08,$85,$08,$85,$10,$85,$10,$85,$08,$85
.ref84:
	.db $bf
.ref85:
	.db $bf
.ref86:
	.db $bf
.ref87:
	.db $bf
.ref88:
	.db $bf
.ref89:
	.db $bf
.ref90:
	.db $bf
.ref91:
	.db $bf
.ref92:
	.db $bf
.ref93:
	.db $bf
.ref94:
	.db $87,$10,$85,$10,$85,$08,$85,$08,$85,$10,$85,$10,$85,$08,$85
	.db $ff,$10
	.dw .ref83
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref96:
	.db $bf
.ref97:
	.db $bf
.ref98:
	.db $bf
.ref99:
	.db $bf
.ref100:
	.db $bf
.ref101:
	.db $bf
.ref102:
	.db $bf
.ref103:
	.db $bf
.ref104:
	.db $bf
.ref105:
	.db $bf
.ref106:
	.db $bf
.ref107:
	.db $bf
.ref108:
	.db $bf
.ref109:
	.db $bf
.ref110:
	.db $bf
.ref111:
	.db $bf
.ref112:
	.db $bf
.ref113:
	.db $bf
.ref114:
	.db $bf
.ref115:
	.db $bf
.ref116:
	.db $bf
.ref117:
	.db $bf
.ref118:
	.db $bf
.ref119:
	.db $bf
	.db $fd
	.dw .song0ch4loop
