;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.dw .ntsc
	.dw .pal
.ntsc:
	.dw .sfx_ntsc_0
	.dw .sfx_ntsc_1
.pal:
	.dw .sfx_pal_0
	.dw .sfx_pal_1

.sfx_ntsc_0:
	.db $80,$ba,$81,$1c,$82,$01,$01,$80,$b7,$01,$80,$b6,$01,$00
.sfx_pal_0:
	.db $80,$ba,$81,$08,$82,$01,$01,$80,$b7,$01,$80,$b6,$01,$00
.sfx_ntsc_1:
	.db $80,$b8,$81,$ab,$82,$01,$01,$80,$b6,$01,$80,$b5,$01,$80,$b4,$01
	.db $80,$b3,$02,$00
.sfx_pal_1:
	.db $80,$b8,$81,$8c,$82,$01,$01,$80,$b6,$01,$80,$b5,$01,$80,$b4,$01
	.db $80,$b3,$01,$00
