;this file for FamiTone2 library generated by text2data tool

Boss_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,409,341

.instruments:
	.db $30 ;instrument $00
	.dw .env6,.env0,.env0
	.db $00
	.db $30 ;instrument $01
	.dw .env1,.env7,.env9
	.db $00
	.db $30 ;instrument $02
	.dw .env1,.env0,.env0
	.db $00
	.db $70 ;instrument $04
	.dw .env2,.env0,.env0
	.db $00
	.db $30 ;instrument $05
	.dw .env3,.env0,.env0
	.db $00
	.db $30 ;instrument $06
	.dw .env4,.env8,.env0
	.db $00
	.db $30 ;instrument $07
	.dw .env1,.env7,.env9
	.db $00
	.db $70 ;instrument $09
	.dw .env5,.env0,.env0
	.db $00
	.db $30 ;instrument $0a
	.dw .env1,.env7,.env9
	.db $00

.samples:
	.db $00+FT_DPCM_PTR,$00,$00	;1
	.db $00+FT_DPCM_PTR,$00,$00	;2
	.db $00+FT_DPCM_PTR,$00,$00	;3
	.db $00+FT_DPCM_PTR,$00,$00	;4
	.db $00+FT_DPCM_PTR,$00,$00	;5
	.db $00+FT_DPCM_PTR,$00,$00	;6
	.db $00+FT_DPCM_PTR,$00,$00	;7
	.db $00+FT_DPCM_PTR,$00,$00	;8
	.db $00+FT_DPCM_PTR,$00,$00	;9
	.db $00+FT_DPCM_PTR,$00,$00	;10
	.db $00+FT_DPCM_PTR,$00,$00	;11
	.db $00+FT_DPCM_PTR,$00,$00	;12
	.db $00+FT_DPCM_PTR,$00,$00	;13
	.db $00+FT_DPCM_PTR,$00,$00	;14
	.db $00+FT_DPCM_PTR,$00,$00	;15
	.db $00+FT_DPCM_PTR,$00,$00	;16
	.db $00+FT_DPCM_PTR,$00,$00	;17
	.db $00+FT_DPCM_PTR,$00,$00	;18
	.db $00+FT_DPCM_PTR,$00,$00	;19
	.db $00+FT_DPCM_PTR,$00,$00	;20
	.db $00+FT_DPCM_PTR,$00,$00	;21
	.db $00+FT_DPCM_PTR,$00,$00	;22
	.db $00+FT_DPCM_PTR,$00,$00	;23
	.db $00+FT_DPCM_PTR,$00,$00	;24
	.db $00+FT_DPCM_PTR,$27,$0f	;25
	.db $00+FT_DPCM_PTR,$00,$00	;26
	.db $0a+FT_DPCM_PTR,$4c,$0f	;27
	.db $00+FT_DPCM_PTR,$00,$00	;28
	.db $1e+FT_DPCM_PTR,$2d,$0f	;29
	.db $2a+FT_DPCM_PTR,$77,$0f	;30
	.db $00+FT_DPCM_PTR,$00,$00	;31
	.db $00+FT_DPCM_PTR,$00,$00	;32
	.db $00+FT_DPCM_PTR,$00,$00	;33
	.db $00+FT_DPCM_PTR,$00,$00	;34
	.db $00+FT_DPCM_PTR,$00,$00	;35
	.db $00+FT_DPCM_PTR,$00,$00	;36
	.db $00+FT_DPCM_PTR,$00,$00	;37
	.db $00+FT_DPCM_PTR,$00,$00	;38
	.db $00+FT_DPCM_PTR,$00,$00	;39
	.db $00+FT_DPCM_PTR,$00,$00	;40
	.db $00+FT_DPCM_PTR,$00,$00	;41
	.db $00+FT_DPCM_PTR,$00,$00	;42
	.db $00+FT_DPCM_PTR,$00,$00	;43
	.db $00+FT_DPCM_PTR,$00,$00	;44
	.db $00+FT_DPCM_PTR,$00,$00	;45
	.db $00+FT_DPCM_PTR,$00,$00	;46
	.db $00+FT_DPCM_PTR,$00,$00	;47
	.db $00+FT_DPCM_PTR,$00,$00	;48
	.db $00+FT_DPCM_PTR,$00,$00	;49
	.db $00+FT_DPCM_PTR,$00,$00	;50
	.db $00+FT_DPCM_PTR,$00,$00	;51
	.db $00+FT_DPCM_PTR,$00,$00	;52
	.db $00+FT_DPCM_PTR,$00,$00	;53
	.db $00+FT_DPCM_PTR,$00,$00	;54
	.db $00+FT_DPCM_PTR,$00,$00	;55
	.db $00+FT_DPCM_PTR,$00,$00	;56
	.db $00+FT_DPCM_PTR,$00,$00	;57
	.db $00+FT_DPCM_PTR,$00,$00	;58
	.db $00+FT_DPCM_PTR,$00,$00	;59
	.db $00+FT_DPCM_PTR,$00,$00	;60
	.db $00+FT_DPCM_PTR,$00,$00	;61
	.db $00+FT_DPCM_PTR,$00,$00	;62
	.db $00+FT_DPCM_PTR,$00,$00	;63

.env0:
	.db $c0,$00,$00
.env1:
	.db $cc,$cc,$cb,$cb,$ca,$c9,$c8,$c6,$c5,$c4,$c3,$c3,$c2,$c1,$c1,$c0
	.db $00,$0f
.env2:
	.db $c1,$c2,$c3,$c4,$c5,$c5,$c6,$c6,$c7,$c7,$c8,$c8,$c9,$c9,$ca,$ca
	.db $cb,$02,$cc,$02,$cd,$05,$cc,$02,$cb,$02,$ca,$04,$c9,$07,$c8,$06
	.db $c7,$c7,$00,$21
.env3:
	.db $cc,$c9,$c6,$c4,$c2,$c0,$00,$05
.env4:
	.db $cf,$cd,$cb,$c9,$c8,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$c2,$c1,$c1,$c0
	.db $00,$0f
.env5:
	.db $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$06,$c6,$02,$c5,$00,$0d
.env6:
	.db $cf,$00,$00
.env7:
	.db $c0,$c0,$c7,$c7,$cc,$cc,$c7,$c7,$00,$00
.env8:
	.db $c0,$02,$c1,$02,$c2,$00,$04
.env9:
	.db $b5,$00,$00


.song0ch0:
	.db $fb,$05
.ref0:
	.db $8e,$1e,$24,$2c,$34,$24,$2c,$34,$36,$2c,$34,$36,$3c,$34,$36,$3c
	.db $4c
.ref1:
	.db $36,$3c,$44,$4c,$3c,$44,$4c,$4e,$44,$4c,$4e,$54,$4c,$4e,$54,$64
.song0ch0loop:
.ref2:
	.db $8e,$67,$4f,$67,$4f,$67,$4f,$67,$4f,$00,$9d
.ref3:
	.db $bf
.ref4:
	.db $84,$4e,$85,$4e,$85,$52,$85,$4e,$85,$58,$85,$54,$85,$52,$85,$54
	.db $85
.ref5:
	.db $4e,$85,$4e,$85,$52,$85,$4e,$85,$58,$85,$54,$85,$58,$85,$58,$85
.ref6:
	.db $bf
.ref7:
	.db $bf
.ref8:
	.db $bf
.ref9:
	.db $bf
.ref10:
	.db $8e,$36,$95,$3b,$3d,$3a,$9d
.ref11:
	.db $3c,$95,$41,$45,$40,$8d,$4a,$8d
.ref12:
	.db $36,$95,$3b,$3d,$3a,$9d
	.db $ff,$08
	.dw .ref11
.ref14:
	.db $4e,$89,$4a,$89,$4e,$a5
.ref15:
	.db $40,$9d,$44,$9d
	.db $ff,$06
	.dw .ref14
.ref17:
	.db $40,$9d,$44,$9d
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.ref18:
	.db $9f
.ref19:
	.db $9f
.song0ch1loop:
.ref20:
	.db $86,$4e,$bd
.ref21:
	.db $bf
.ref22:
	.db $4e,$bd
.ref23:
	.db $b7,$8e,$4f,$54,$81
.ref24:
	.db $58,$95,$55,$53,$54,$95,$53,$54,$81
.ref25:
	.db $53,$4f,$4a,$8d,$44,$8d,$4a,$8d,$45,$4a,$81
.ref26:
	.db $4c,$8d,$4b,$4f,$4b,$49,$44,$89,$3c,$89,$44,$85
.ref27:
	.db $48,$89,$40,$89,$52,$85,$58,$89,$54,$89,$58,$85
.ref28:
	.db $5c,$bd
.ref29:
	.db $bf
.ref30:
	.db $4e,$95,$53,$55,$52,$9d
.ref31:
	.db $54,$95,$59,$5d,$58,$8d,$62,$8d
.ref32:
	.db $66,$89,$62,$89,$5c,$a5
.ref33:
	.db $58,$85,$58,$85,$55,$58,$85,$59,$5c,$85,$58,$85,$54,$85,$52,$85
	.db $ff,$06
	.dw .ref32
.ref35:
	.db $58,$85,$58,$85,$55,$58,$85,$59,$74,$85,$70,$85,$6c,$85,$6a,$85
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.ref36:
	.db $9f
.ref37:
	.db $9f
.song0ch2loop:
.ref38:
	.db $bf
.ref39:
	.db $bf
.ref40:
	.db $bf
.ref41:
	.db $bf
.ref42:
	.db $bf
.ref43:
	.db $bf
.ref44:
	.db $bf
.ref45:
	.db $bf
.ref46:
	.db $bf
.ref47:
	.db $bf
.ref48:
	.db $bf
.ref49:
	.db $bf
.ref50:
	.db $bf
.ref51:
	.db $bf
.ref52:
	.db $bf
.ref53:
	.db $bf
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.ref54:
	.db $88,$1a,$85,$1a,$85,$1a,$85,$1a,$85
.ref55:
	.db $8a,$0f,$88,$0b,$8a,$0f,$88,$0b,$8a,$1b,$12,$12,$10,$10,$0e,$0e
.song0ch3loop:
.ref56:
	.db $88,$0b,$0b,$8a,$0d,$88,$0b,$0b,$0b,$8a,$0d,$88,$0a,$0a,$0b,$0b
	.db $8a,$0d,$88,$0b,$0b,$0b,$8a,$0d,$88,$0a,$0a
.ref57:
	.db $8a,$0d,$88,$0b,$8a,$0d,$88,$0b,$0b,$0b,$8a,$0d,$88,$0a,$0a,$0b
	.db $8a,$0d,$0d,$0d,$88,$0b,$8a,$0d,$0d,$88,$0a,$0a
.ref58:
	.db $0b,$0b,$8a,$0d,$88,$0b,$0b,$0b,$8a,$0d,$88,$0a,$0a,$0b,$0b,$8a
	.db $0d,$88,$0b,$0b,$0b,$8a,$0d,$88,$0a,$0a
	.db $ff,$12
	.dw .ref57
	.db $ff,$12
	.dw .ref58
	.db $ff,$12
	.dw .ref58
	.db $ff,$12
	.dw .ref58
	.db $ff,$12
	.dw .ref58
.ref64:
	.db $8a,$0d,$88,$0b,$0b,$0b,$8a,$0d,$88,$0b,$0b,$0b,$8a,$0d,$88,$0b
	.db $0b,$0a,$0a,$8a,$0d,$88,$0b,$0b,$0a,$81
.ref65:
	.db $8a,$0d,$88,$0b,$0b,$0b,$8a,$0d,$88,$0b,$0b,$0a,$0a,$8a,$0d,$88
	.db $0b,$0b,$0a,$0a,$0b,$0b,$8a,$0d,$88,$0a,$81
.ref66:
	.db $8a,$0d,$88,$0b,$8a,$0d,$88,$0b,$8a,$0d,$88,$0b,$8a,$0d,$88,$0b
	.db $8a,$0d,$88,$0b,$8a,$0d,$88,$0a,$0a,$8a,$0d,$88,$0b,$8a,$0d,$88
	.db $0a,$81
.ref67:
	.db $8a,$0d,$88,$0b,$8a,$0d,$88,$0b,$8a,$0d,$88,$0b,$8a,$0d,$88,$0a
	.db $0a,$8a,$0d,$0d,$0d,$0d,$0d,$0c,$0c,$0c,$0c,$0c,$0c
.ref68:
	.db $0c,$85,$88,$0b,$8a,$0c,$85,$88,$0b,$8a,$0d,$88,$0a,$0a,$0b,$0b
	.db $8a,$0d,$0d,$0d,$0d,$0d,$0c,$88,$0a
	.db $ff,$12
	.dw .ref58
.ref70:
	.db $8a,$0c,$85,$88,$0b,$8a,$0c,$85,$88,$0b,$8a,$0d,$88,$0a,$0a,$0b
	.db $0b,$8a,$0d,$0d,$0d,$0d,$0d,$0c,$88,$0a
	.db $ff,$12
	.dw .ref58
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.ref72:
	.db $9f
.ref73:
	.db $8f,$3c,$85,$36,$3c,$32,$32
.song0ch4loop:
.ref74:
	.db $32,$85,$36,$85,$32,$85,$36,$85,$32,$85,$36,$85,$32,$85,$36,$85
	.db $ff,$10
	.dw .ref74
	.db $ff,$10
	.dw .ref74
	.db $ff,$10
	.dw .ref74
	.db $ff,$10
	.dw .ref74
	.db $ff,$10
	.dw .ref74
	.db $ff,$10
	.dw .ref74
	.db $ff,$10
	.dw .ref74
.ref82:
	.db $37,$33,$33,$33,$37,$33,$33,$33,$37,$33,$33,$33,$37,$33,$33,$32
	.db $81
	.db $ff,$11
	.dw .ref82
.ref84:
	.db $37,$33,$37,$33,$37,$33,$37,$33,$37,$33,$37,$33,$37,$33,$37,$32
	.db $81
.ref85:
	.db $37,$33,$37,$33,$37,$33,$37,$33,$37,$33,$37,$33,$36,$8d
.ref86:
	.db $36,$85,$33,$36,$89,$36,$85,$32,$85,$37,$37,$37,$37,$37,$36,$81
	.db $ff,$10
	.dw .ref74
	.db $ff,$10
	.dw .ref86
	.db $ff,$10
	.dw .ref74
	.db $fd
	.dw .song0ch4loop
