;this file for FamiTone2 library generated by text2data tool

IntroJingle_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $30 ;instrument $01
	.dw .env1,.env0,.env0
	.db $00
	.db $b0 ;instrument $02
	.dw .env1,.env2,.env0
	.db $00
	.db $b0 ;instrument $04
	.dw .env1,.env2,.env0
	.db $00
	.db $b0 ;instrument $05
	.dw .env1,.env2,.env0
	.db $00
	.db $b0 ;instrument $06
	.dw .env1,.env2,.env0
	.db $00
	.db $b0 ;instrument $07
	.dw .env1,.env2,.env0
	.db $00
	.db $b0 ;instrument $09
	.dw .env1,.env2,.env0
	.db $00
	.db $b0 ;instrument $0a
	.dw .env1,.env2,.env0
	.db $00
	.db $b0 ;instrument $0b
	.dw .env1,.env2,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $cb,$c8,$c6,$c4,$c3,$c2,$c1,$04,$c0,$00,$08
.env2:
	.db $c0,$c0,$c3,$c3,$c7,$c7,$00,$00


.song0ch0:
	.db $fb,$02
.song0ch0loop:
.ref0:
	.db $80,$25,$28,$24,$2a,$28,$2e,$2a,$38,$2e,$40,$38,$46,$40,$50,$46
	.db $54,$50,$58,$54,$5e,$58,$62,$5e,$68,$62,$70,$68,$72,$70,$76,$72
	.db $76,$85,$76,$85,$76,$85,$76,$85,$76,$85,$76,$85,$76,$85,$76,$85
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref1:
	.db $f9,$85
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref2:
	.db $f9,$85
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref3:
	.db $f9,$85
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref4:
	.db $f9,$85
	.db $fd
	.dw .song0ch4loop
