;this file for FamiTone2 library generated by text2data tool

Map_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,286,238

.instruments:
	.db $30 ;instrument $00
	.dw .env5,.env0,.env0
	.db $00
	.db $30 ;instrument $01
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $04
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $05
	.dw .env2,.env0,.env0
	.db $00
	.db $30 ;instrument $06
	.dw .env3,.env0,.env0
	.db $00
	.db $30 ;instrument $07
	.dw .env5,.env0,.env0
	.db $00
	.db $70 ;instrument $09
	.dw .env4,.env6,.env0
	.db $00
	.db $70 ;instrument $0a
	.dw .env4,.env7,.env0
	.db $00

.samples:
	.db $00+FT_DPCM_PTR,$00,$00	;1
	.db $00+FT_DPCM_PTR,$00,$00	;2
	.db $00+FT_DPCM_PTR,$00,$00	;3
	.db $00+FT_DPCM_PTR,$00,$00	;4
	.db $00+FT_DPCM_PTR,$00,$00	;5
	.db $00+FT_DPCM_PTR,$00,$00	;6
	.db $00+FT_DPCM_PTR,$00,$00	;7
	.db $00+FT_DPCM_PTR,$00,$00	;8
	.db $00+FT_DPCM_PTR,$00,$00	;9
	.db $00+FT_DPCM_PTR,$00,$00	;10
	.db $00+FT_DPCM_PTR,$00,$00	;11
	.db $00+FT_DPCM_PTR,$00,$00	;12
	.db $00+FT_DPCM_PTR,$00,$00	;13
	.db $00+FT_DPCM_PTR,$00,$00	;14
	.db $00+FT_DPCM_PTR,$00,$00	;15
	.db $00+FT_DPCM_PTR,$00,$00	;16
	.db $00+FT_DPCM_PTR,$00,$00	;17
	.db $00+FT_DPCM_PTR,$00,$00	;18
	.db $00+FT_DPCM_PTR,$00,$00	;19
	.db $00+FT_DPCM_PTR,$00,$00	;20
	.db $00+FT_DPCM_PTR,$00,$00	;21
	.db $00+FT_DPCM_PTR,$00,$00	;22
	.db $00+FT_DPCM_PTR,$00,$00	;23
	.db $00+FT_DPCM_PTR,$00,$00	;24
	.db $00+FT_DPCM_PTR,$27,$0f	;25
	.db $00+FT_DPCM_PTR,$00,$00	;26
	.db $0a+FT_DPCM_PTR,$4c,$0f	;27
	.db $00+FT_DPCM_PTR,$00,$00	;28
	.db $1e+FT_DPCM_PTR,$2d,$0f	;29
	.db $2a+FT_DPCM_PTR,$77,$0f	;30
	.db $00+FT_DPCM_PTR,$00,$00	;31
	.db $00+FT_DPCM_PTR,$00,$00	;32
	.db $00+FT_DPCM_PTR,$00,$00	;33
	.db $00+FT_DPCM_PTR,$00,$00	;34
	.db $00+FT_DPCM_PTR,$00,$00	;35
	.db $00+FT_DPCM_PTR,$00,$00	;36
	.db $00+FT_DPCM_PTR,$00,$00	;37
	.db $00+FT_DPCM_PTR,$00,$00	;38
	.db $00+FT_DPCM_PTR,$00,$00	;39
	.db $00+FT_DPCM_PTR,$00,$00	;40
	.db $00+FT_DPCM_PTR,$00,$00	;41
	.db $00+FT_DPCM_PTR,$00,$00	;42
	.db $00+FT_DPCM_PTR,$00,$00	;43
	.db $00+FT_DPCM_PTR,$00,$00	;44
	.db $00+FT_DPCM_PTR,$00,$00	;45
	.db $00+FT_DPCM_PTR,$00,$00	;46
	.db $00+FT_DPCM_PTR,$00,$00	;47
	.db $00+FT_DPCM_PTR,$00,$00	;48
	.db $00+FT_DPCM_PTR,$00,$00	;49
	.db $00+FT_DPCM_PTR,$00,$00	;50
	.db $00+FT_DPCM_PTR,$00,$00	;51
	.db $00+FT_DPCM_PTR,$00,$00	;52
	.db $00+FT_DPCM_PTR,$00,$00	;53
	.db $00+FT_DPCM_PTR,$00,$00	;54
	.db $00+FT_DPCM_PTR,$00,$00	;55
	.db $00+FT_DPCM_PTR,$00,$00	;56
	.db $00+FT_DPCM_PTR,$00,$00	;57
	.db $00+FT_DPCM_PTR,$00,$00	;58
	.db $00+FT_DPCM_PTR,$00,$00	;59
	.db $00+FT_DPCM_PTR,$00,$00	;60
	.db $00+FT_DPCM_PTR,$00,$00	;61
	.db $00+FT_DPCM_PTR,$00,$00	;62
	.db $00+FT_DPCM_PTR,$00,$00	;63

.env0:
	.db $c0,$00,$00
.env1:
	.db $ca,$c9,$c7,$c6,$c5,$c4,$c3,$04,$c3,$00,$08
.env2:
	.db $cb,$c7,$c4,$c3,$c2,$02,$c1,$02,$c0,$00,$08
.env3:
	.db $ca,$c7,$c6,$c5,$c4,$c3,$03,$c2,$06,$c1,$04,$c0,$00,$0b
.env4:
	.db $cb,$00,$00
.env5:
	.db $cf,$00,$00
.env6:
	.db $c0,$c0,$c3,$c3,$c7,$c7,$c3,$c3,$00,$00
.env7:
	.db $c0,$c0,$c4,$c4,$c7,$c7,$c3,$c3,$00,$00


.song0ch0:
	.db $fb,$08
.song0ch0loop:
.ref0:
	.db $8c,$3c,$bd
.ref1:
	.db $8e,$38,$bd
.ref2:
	.db $8c,$3c,$bd
.ref3:
	.db $8e,$38,$bd
.ref4:
	.db $8c,$3a,$bd
.ref5:
	.db $8e,$36,$bd
.ref6:
	.db $8c,$3a,$bd
.ref7:
	.db $8e,$36,$bd
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref8:
	.db $82,$72,$76,$70,$72,$68,$70,$62,$68,$5e,$62,$58,$5e,$54,$58,$50
	.db $54,$46,$50,$40,$46,$38,$40,$2e,$38,$2a,$2e,$28,$2a,$24,$29,$24
.ref9:
	.db $68,$76,$76,$68,$72,$76,$70,$72,$68,$70,$62,$68,$5e,$62,$58,$5e
	.db $50,$58,$4a,$50,$46,$4a,$42,$46,$40,$42,$38,$40,$32,$38,$2e,$32
.ref10:
	.db $72,$76,$70,$72,$68,$70,$62,$68,$5e,$62,$58,$5e,$54,$58,$50,$54
	.db $46,$50,$40,$46,$38,$40,$2e,$38,$2a,$2e,$28,$2a,$24,$29,$24
	.db $ff,$20
	.dw .ref9
.ref12:
	.db $70,$74,$6e,$70,$66,$6e,$60,$66,$5c,$60,$56,$5c,$52,$56,$4e,$52
	.db $44,$4e,$3e,$44,$36,$3e,$2c,$36,$28,$2c,$26,$28,$22,$27,$0a
.ref13:
	.db $66,$74,$74,$66,$70,$74,$6e,$70,$66,$6e,$60,$66,$5c,$60,$56,$5c
	.db $4e,$56,$48,$4e,$44,$48,$40,$44,$3e,$40,$36,$3e,$30,$36,$2c,$30
	.db $ff,$1f
	.dw .ref12
	.db $ff,$20
	.dw .ref13
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref16:
	.db $8a,$24,$00,$28,$00,$24,$00,$2e,$00,$24,$00,$28,$00,$24,$00,$2e
	.db $00,$24,$00,$28,$00,$24,$00,$2e,$00,$24,$00,$28,$00,$24,$00,$2e
	.db $00
.ref17:
	.db $24,$00,$28,$00,$24,$00,$2e,$00,$24,$00,$28,$00,$24,$00,$2e,$00
	.db $24,$00,$28,$00,$24,$00,$2e,$00,$24,$00,$28,$00,$24,$00,$2e,$00
	.db $ff,$20
	.dw .ref17
	.db $ff,$20
	.dw .ref17
.ref20:
	.db $22,$00,$26,$00,$22,$00,$2c,$00,$22,$00,$26,$00,$22,$00,$2c,$00
	.db $22,$00,$26,$00,$22,$00,$2c,$00,$22,$00,$26,$00,$22,$00,$2c,$00
	.db $ff,$20
	.dw .ref20
	.db $ff,$20
	.dw .ref20
	.db $ff,$20
	.dw .ref20
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref24:
	.db $86,$21,$84,$1d,$1d,$1d,$88,$1b,$84,$1d,$1d,$1d,$86,$21,$84,$1c
	.db $1c,$86,$21,$84,$1d,$88,$1b,$84,$1d,$88,$1b,$1a,$81
.ref25:
	.db $86,$21,$84,$1d,$1d,$1d,$88,$1b,$84,$1d,$86,$21,$84,$1d,$86,$21
	.db $84,$1c,$1c,$86,$21,$84,$1d,$88,$1b,$84,$1d,$88,$1b,$1a,$81
	.db $ff,$12
	.dw .ref24
	.db $ff,$12
	.dw .ref25
	.db $ff,$12
	.dw .ref25
	.db $ff,$12
	.dw .ref25
	.db $ff,$12
	.dw .ref25
	.db $ff,$12
	.dw .ref25
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref32:
	.db $32,$8d,$36,$85,$33,$3b,$33,$3d,$32,$85,$36,$85,$37,$36,$81
	.db $ff,$0f
	.dw .ref32
	.db $ff,$0f
	.dw .ref32
	.db $ff,$0f
	.dw .ref32
	.db $ff,$0f
	.dw .ref32
	.db $ff,$0f
	.dw .ref32
	.db $ff,$0f
	.dw .ref32
	.db $ff,$0f
	.dw .ref32
	.db $fd
	.dw .song0ch4loop
