;this file for FamiTone2 library generated by text2data tool

Mars_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,280,233

.instruments:
	.db $30 ;instrument $00
	.dw .env4,.env0,.env0
	.db $00
	.db $30 ;instrument $04
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $05
	.dw .env2,.env0,.env0
	.db $00
	.db $30 ;instrument $06
	.dw .env3,.env0,.env0
	.db $00
	.db $30 ;instrument $07
	.dw .env4,.env0,.env0
	.db $00
	.db $70 ;instrument $0d
	.dw .env5,.env0,.env0
	.db $00
	.db $70 ;instrument $0e
	.dw .env6,.env0,.env0
	.db $00

.samples:
	.db $00+FT_DPCM_PTR,$00,$00	;1
	.db $00+FT_DPCM_PTR,$00,$00	;2
	.db $00+FT_DPCM_PTR,$00,$00	;3
	.db $00+FT_DPCM_PTR,$00,$00	;4
	.db $00+FT_DPCM_PTR,$00,$00	;5
	.db $00+FT_DPCM_PTR,$00,$00	;6
	.db $00+FT_DPCM_PTR,$00,$00	;7
	.db $00+FT_DPCM_PTR,$00,$00	;8
	.db $00+FT_DPCM_PTR,$00,$00	;9
	.db $00+FT_DPCM_PTR,$00,$00	;10
	.db $00+FT_DPCM_PTR,$00,$00	;11
	.db $00+FT_DPCM_PTR,$00,$00	;12
	.db $00+FT_DPCM_PTR,$00,$00	;13
	.db $00+FT_DPCM_PTR,$00,$00	;14
	.db $00+FT_DPCM_PTR,$00,$00	;15
	.db $00+FT_DPCM_PTR,$00,$00	;16
	.db $00+FT_DPCM_PTR,$00,$00	;17
	.db $00+FT_DPCM_PTR,$00,$00	;18
	.db $00+FT_DPCM_PTR,$00,$00	;19
	.db $00+FT_DPCM_PTR,$00,$00	;20
	.db $00+FT_DPCM_PTR,$00,$00	;21
	.db $00+FT_DPCM_PTR,$00,$00	;22
	.db $00+FT_DPCM_PTR,$00,$00	;23
	.db $00+FT_DPCM_PTR,$00,$00	;24
	.db $00+FT_DPCM_PTR,$27,$0f	;25
	.db $00+FT_DPCM_PTR,$00,$00	;26
	.db $0a+FT_DPCM_PTR,$4c,$0f	;27
	.db $00+FT_DPCM_PTR,$00,$00	;28
	.db $1e+FT_DPCM_PTR,$2d,$0f	;29
	.db $2a+FT_DPCM_PTR,$77,$0f	;30
	.db $00+FT_DPCM_PTR,$00,$00	;31
	.db $00+FT_DPCM_PTR,$00,$00	;32
	.db $00+FT_DPCM_PTR,$00,$00	;33
	.db $00+FT_DPCM_PTR,$00,$00	;34
	.db $00+FT_DPCM_PTR,$00,$00	;35
	.db $00+FT_DPCM_PTR,$00,$00	;36
	.db $00+FT_DPCM_PTR,$00,$00	;37
	.db $00+FT_DPCM_PTR,$00,$00	;38
	.db $00+FT_DPCM_PTR,$00,$00	;39
	.db $00+FT_DPCM_PTR,$00,$00	;40
	.db $00+FT_DPCM_PTR,$00,$00	;41
	.db $00+FT_DPCM_PTR,$00,$00	;42
	.db $00+FT_DPCM_PTR,$00,$00	;43
	.db $00+FT_DPCM_PTR,$00,$00	;44
	.db $00+FT_DPCM_PTR,$00,$00	;45
	.db $00+FT_DPCM_PTR,$00,$00	;46
	.db $00+FT_DPCM_PTR,$00,$00	;47
	.db $00+FT_DPCM_PTR,$00,$00	;48
	.db $00+FT_DPCM_PTR,$00,$00	;49
	.db $00+FT_DPCM_PTR,$00,$00	;50
	.db $00+FT_DPCM_PTR,$00,$00	;51
	.db $00+FT_DPCM_PTR,$00,$00	;52
	.db $00+FT_DPCM_PTR,$00,$00	;53
	.db $00+FT_DPCM_PTR,$00,$00	;54
	.db $00+FT_DPCM_PTR,$00,$00	;55
	.db $00+FT_DPCM_PTR,$00,$00	;56
	.db $00+FT_DPCM_PTR,$00,$00	;57
	.db $00+FT_DPCM_PTR,$00,$00	;58
	.db $00+FT_DPCM_PTR,$00,$00	;59
	.db $00+FT_DPCM_PTR,$00,$00	;60
	.db $00+FT_DPCM_PTR,$00,$00	;61
	.db $00+FT_DPCM_PTR,$00,$00	;62
	.db $00+FT_DPCM_PTR,$00,$00	;63

.env0:
	.db $c0,$00,$00
.env1:
	.db $c8,$c5,$c3,$c2,$02,$c1,$04,$c0,$00,$07
.env2:
	.db $cd,$ca,$c7,$c6,$c5,$c4,$c4,$c3,$c3,$c2,$c1,$c0,$00,$0b
.env3:
	.db $c9,$c6,$c5,$c4,$c4,$c3,$03,$c2,$02,$c1,$c1,$c0,$00,$0b
.env4:
	.db $cf,$00,$00
.env5:
	.db $cf,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c3,$c2,$c2,$c1
	.db $00,$0f
.env6:
	.db $c5,$02,$c6,$c6,$c7,$c7,$c8,$c8,$c9,$ca,$cb,$cc,$cd,$ce,$02,$cf
	.db $cf,$cf,$00,$11


.song0ch0:
	.db $fb,$05
.song0ch0loop:
.ref0:
	.db $00,$bd
.ref1:
	.db $bf
.ref2:
	.db $8a,$29,$29,$28,$85,$28,$85,$28,$85,$29,$29,$28,$85,$28,$85,$8c
	.db $36,$85
.ref3:
	.db $8a,$29,$29,$28,$85,$28,$85,$28,$85,$29,$29,$28,$85,$28,$85,$8c
	.db $38,$85
.ref4:
	.db $8a,$59,$4f,$47,$41,$59,$4f,$47,$41,$59,$4f,$47,$41,$47,$41,$59
	.db $4e,$81
.ref5:
	.db $5d,$53,$4d,$45,$5d,$53,$4d,$45,$5d,$53,$4d,$45,$5d,$5f,$5d,$54
	.db $81
.ref6:
	.db $59,$4f,$47,$41,$59,$4f,$47,$41,$59,$4f,$47,$41,$47,$41,$59,$4e
	.db $81
	.db $ff,$11
	.dw .ref5
	.db $ff,$11
	.dw .ref6
	.db $ff,$11
	.dw .ref5
.ref10:
	.db $59,$4f,$59,$4f,$59,$4f,$59,$4f,$59,$4f,$59,$4f,$59,$4f,$59,$4e
	.db $81
.ref11:
	.db $41,$41,$40,$85,$40,$85,$40,$85,$41,$41,$40,$85,$40,$85,$40,$85
	.db $ff,$10
	.dw .ref11
	.db $ff,$10
	.dw .ref11
	.db $ff,$10
	.dw .ref11
	.db $ff,$10
	.dw .ref11
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref16:
	.db $8a,$11,$11,$10,$85,$10,$85,$10,$85,$11,$11,$10,$85,$10,$85,$8c
	.db $1e,$85
.ref17:
	.db $8a,$11,$11,$10,$85,$10,$85,$10,$85,$11,$11,$10,$85,$10,$85,$8c
	.db $20,$85
	.db $ff,$10
	.dw .ref16
	.db $ff,$10
	.dw .ref17
	.db $ff,$10
	.dw .ref16
	.db $ff,$10
	.dw .ref17
	.db $ff,$10
	.dw .ref16
	.db $ff,$10
	.dw .ref17
	.db $ff,$10
	.dw .ref16
	.db $ff,$10
	.dw .ref17
	.db $ff,$10
	.dw .ref16
	.db $ff,$10
	.dw .ref17
	.db $ff,$10
	.dw .ref16
	.db $ff,$10
	.dw .ref17
	.db $ff,$10
	.dw .ref16
	.db $ff,$10
	.dw .ref17
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref32:
	.db $88,$28,$00,$28,$00,$28,$00,$83,$28,$00,$83,$28,$00,$83,$28,$00
	.db $28,$00,$28,$00,$83,$28,$00,$83,$29,$00,$81
.ref33:
	.db $28,$00,$28,$00,$28,$00,$83,$28,$00,$83,$28,$00,$83,$28,$00,$28
	.db $00,$28,$00,$83,$28,$00,$83,$29,$00,$81
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $ff,$1a
	.dw .ref33
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref48:
	.db $86,$11,$11,$11,$82,$1f,$86,$11,$82,$1f,$86,$10,$10,$10,$10,$11
	.db $11,$11,$82,$1f,$86,$11,$82,$1f,$86,$11,$82,$1e,$81
	.db $ff,$13
	.dw .ref48
	.db $ff,$13
	.dw .ref48
	.db $ff,$13
	.dw .ref48
.ref52:
	.db $84,$21,$82,$1d,$1d,$1d,$84,$11,$82,$1d,$1d,$1d,$84,$21,$82,$1c
	.db $1c,$84,$21,$82,$1d,$84,$11,$82,$1d,$84,$11,$10,$81
.ref53:
	.db $21,$82,$1d,$1d,$1d,$84,$11,$82,$1d,$84,$21,$82,$1d,$84,$21,$82
	.db $1c,$1c,$84,$21,$82,$1d,$84,$11,$82,$1d,$84,$11,$10,$81
.ref54:
	.db $21,$82,$1d,$1d,$1d,$84,$11,$82,$1d,$1d,$1d,$84,$21,$82,$1c,$1c
	.db $84,$21,$82,$1d,$84,$11,$82,$1d,$84,$11,$10,$81
	.db $ff,$12
	.dw .ref53
	.db $ff,$12
	.dw .ref54
	.db $ff,$12
	.dw .ref53
	.db $ff,$12
	.dw .ref54
	.db $ff,$13
	.dw .ref48
	.db $ff,$13
	.dw .ref48
	.db $ff,$13
	.dw .ref48
	.db $ff,$13
	.dw .ref48
	.db $ff,$13
	.dw .ref48
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref64:
	.db $bf
.ref65:
	.db $bf
.ref66:
	.db $bf
.ref67:
	.db $bf
.ref68:
	.db $32,$9d,$32,$9d
.ref69:
	.db $32,$9d,$32,$9d
.ref70:
	.db $32,$9d,$32,$9d
.ref71:
	.db $32,$9d,$32,$9d
.ref72:
	.db $32,$9d,$32,$9d
.ref73:
	.db $32,$9d,$32,$9d
.ref74:
	.db $32,$9d,$32,$9d
.ref75:
	.db $32,$bd
.ref76:
	.db $bf
.ref77:
	.db $bf
.ref78:
	.db $bf
.ref79:
	.db $bf
	.db $fd
	.dw .song0ch4loop
