;this file for FamiTone2 library generated by text2data tool

Venus_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,409,341

.instruments:
	.db $30 ;instrument $00
	.dw .env3,.env0,.env0
	.db $00
	.db $30 ;instrument $02
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $04
	.dw .env2,.env6,.env0
	.db $00
	.db $30 ;instrument $08
	.dw .env4,.env7,.env0
	.db $00
	.db $30 ;instrument $0d
	.dw .env3,.env0,.env0
	.db $00
	.db $30 ;instrument $12
	.dw .env5,.env0,.env0
	.db $00

.samples:
	.db $00+FT_DPCM_PTR,$00,$00	;1
	.db $00+FT_DPCM_PTR,$00,$00	;2
	.db $00+FT_DPCM_PTR,$00,$00	;3
	.db $00+FT_DPCM_PTR,$00,$00	;4
	.db $00+FT_DPCM_PTR,$00,$00	;5
	.db $00+FT_DPCM_PTR,$00,$00	;6
	.db $00+FT_DPCM_PTR,$00,$00	;7
	.db $00+FT_DPCM_PTR,$00,$00	;8
	.db $00+FT_DPCM_PTR,$00,$00	;9
	.db $00+FT_DPCM_PTR,$00,$00	;10
	.db $00+FT_DPCM_PTR,$00,$00	;11
	.db $00+FT_DPCM_PTR,$00,$00	;12
	.db $00+FT_DPCM_PTR,$00,$00	;13
	.db $00+FT_DPCM_PTR,$00,$00	;14
	.db $00+FT_DPCM_PTR,$00,$00	;15
	.db $00+FT_DPCM_PTR,$00,$00	;16
	.db $00+FT_DPCM_PTR,$00,$00	;17
	.db $00+FT_DPCM_PTR,$00,$00	;18
	.db $00+FT_DPCM_PTR,$00,$00	;19
	.db $00+FT_DPCM_PTR,$00,$00	;20
	.db $00+FT_DPCM_PTR,$00,$00	;21
	.db $00+FT_DPCM_PTR,$00,$00	;22
	.db $00+FT_DPCM_PTR,$00,$00	;23
	.db $00+FT_DPCM_PTR,$00,$00	;24
	.db $00+FT_DPCM_PTR,$27,$0f	;25
	.db $00+FT_DPCM_PTR,$00,$00	;26
	.db $0a+FT_DPCM_PTR,$4c,$0f	;27
	.db $00+FT_DPCM_PTR,$00,$00	;28
	.db $1e+FT_DPCM_PTR,$2d,$0f	;29
	.db $2a+FT_DPCM_PTR,$77,$0f	;30
	.db $00+FT_DPCM_PTR,$00,$00	;31
	.db $00+FT_DPCM_PTR,$00,$00	;32
	.db $00+FT_DPCM_PTR,$00,$00	;33
	.db $00+FT_DPCM_PTR,$00,$00	;34
	.db $00+FT_DPCM_PTR,$00,$00	;35
	.db $00+FT_DPCM_PTR,$00,$00	;36
	.db $00+FT_DPCM_PTR,$00,$00	;37
	.db $00+FT_DPCM_PTR,$00,$00	;38
	.db $00+FT_DPCM_PTR,$00,$00	;39
	.db $00+FT_DPCM_PTR,$00,$00	;40
	.db $00+FT_DPCM_PTR,$00,$00	;41
	.db $00+FT_DPCM_PTR,$00,$00	;42
	.db $00+FT_DPCM_PTR,$00,$00	;43
	.db $00+FT_DPCM_PTR,$00,$00	;44
	.db $00+FT_DPCM_PTR,$00,$00	;45
	.db $00+FT_DPCM_PTR,$00,$00	;46
	.db $00+FT_DPCM_PTR,$00,$00	;47
	.db $00+FT_DPCM_PTR,$00,$00	;48
	.db $00+FT_DPCM_PTR,$00,$00	;49
	.db $00+FT_DPCM_PTR,$00,$00	;50
	.db $00+FT_DPCM_PTR,$00,$00	;51
	.db $00+FT_DPCM_PTR,$00,$00	;52
	.db $00+FT_DPCM_PTR,$00,$00	;53
	.db $00+FT_DPCM_PTR,$00,$00	;54
	.db $00+FT_DPCM_PTR,$00,$00	;55
	.db $00+FT_DPCM_PTR,$00,$00	;56
	.db $00+FT_DPCM_PTR,$00,$00	;57
	.db $00+FT_DPCM_PTR,$00,$00	;58
	.db $00+FT_DPCM_PTR,$00,$00	;59
	.db $00+FT_DPCM_PTR,$00,$00	;60
	.db $00+FT_DPCM_PTR,$00,$00	;61
	.db $00+FT_DPCM_PTR,$00,$00	;62
	.db $00+FT_DPCM_PTR,$00,$00	;63

.env0:
	.db $c0,$00,$00
.env1:
	.db $cc,$c9,$c6,$c4,$c2,$c0,$00,$05
.env2:
	.db $cc,$c9,$c9,$c8,$02,$c6,$c5,$c5,$c4,$c4,$c3,$c2,$c1,$c1,$c0,$00
	.db $0e
.env3:
	.db $cf,$00,$00
.env4:
	.db $cc,$03,$cb,$02,$ca,$ca,$c9,$c6,$04,$c5,$05,$c4,$05,$c3,$05,$c2
	.db $05,$c1,$04,$c0,$00,$13
.env5:
	.db $cf,$ce,$cd,$cd,$cc,$cb,$ca,$ca,$c9,$02,$c8,$c7,$c6,$c6,$c5,$02
	.db $c4,$c3,$c2,$02,$c1,$04,$c0,$00,$16
.env6:
	.db $c0,$02,$c1,$02,$c2,$00,$04
.env7:
	.db $c0,$c0,$c4,$00,$02


.song0ch0:
	.db $fb,$08
.song0ch0loop:
.ref0:
	.db $8a,$4a,$40,$38,$32,$4a,$40,$38,$32,$4a,$40,$38,$32,$4a,$40,$38
	.db $32,$40,$36,$2e,$28,$40,$36,$2e,$28,$40,$36,$2e,$28,$40,$36,$2e
	.db $28
.ref1:
	.db $42,$38,$2e,$2a,$42,$38,$2e,$2a,$42,$38,$2e,$2a,$42,$38,$2e,$2a
	.db $3c,$32,$2a,$24,$3c,$32,$2a,$24,$3c,$32,$2a,$24,$3c,$32,$2a,$24
.ref2:
	.db $4a,$40,$38,$32,$4a,$40,$38,$32,$4a,$40,$38,$32,$4a,$40,$38,$32
	.db $40,$36,$2e,$28,$40,$36,$2e,$28,$40,$36,$2e,$28,$40,$36,$2e,$28
	.db $ff,$20
	.dw .ref1
.ref4:
	.db $4a,$85,$4f,$50,$85,$4f,$4b,$47,$40,$85,$47,$36,$85,$47,$36,$85
.ref5:
	.db $39,$3d,$43,$42,$85,$41,$43,$47,$4a,$8d,$48,$8d
	.db $ff,$10
	.dw .ref4
.ref7:
	.db $39,$3d,$43,$42,$85,$41,$43,$47,$50,$8d,$54,$8d
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref8:
	.db $bf
.ref9:
	.db $bf
.ref10:
	.db $bf
.ref11:
	.db $bf
.ref12:
	.db $bf
.ref13:
	.db $bf
.ref14:
	.db $bf
.ref15:
	.db $bf
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref16:
	.db $bf
.ref17:
	.db $bf
.ref18:
	.db $bf
.ref19:
	.db $bf
.ref20:
	.db $bf
.ref21:
	.db $bf
.ref22:
	.db $bf
.ref23:
	.db $bf
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref24:
	.db $86,$11,$84,$17,$82,$09,$84,$16,$85,$17,$82,$09,$84,$16,$1a,$83
	.db $17,$82,$09,$84,$16,$85,$17,$82,$09,$84,$16,$1a
	.db $ff,$12
	.dw .ref24
	.db $ff,$12
	.dw .ref24
	.db $ff,$12
	.dw .ref24
	.db $ff,$12
	.dw .ref24
	.db $ff,$12
	.dw .ref24
	.db $ff,$12
	.dw .ref24
	.db $ff,$12
	.dw .ref24
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref32:
	.db $32,$85,$3a,$85,$32,$85,$3a,$85,$32,$85,$3a,$85,$32,$85,$3a,$85
	.db $ff,$10
	.dw .ref32
	.db $ff,$10
	.dw .ref32
	.db $ff,$10
	.dw .ref32
	.db $ff,$10
	.dw .ref32
	.db $ff,$10
	.dw .ref32
	.db $ff,$10
	.dw .ref32
	.db $ff,$10
	.dw .ref32
	.db $fd
	.dw .song0ch4loop
