;this file for FamiTone2 library generated by text2data tool

WarpJingle_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $b0 ;instrument $01
	.dw .env0,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00


.song0ch0:
	.db $fb,$02
.song0ch0loop:
.ref0:
	.db $80,$77,$73,$71,$69,$63,$5f,$59,$55,$51,$47,$41,$39,$2f,$24,$85
	.db $24,$85,$24,$85,$24,$85,$24,$85,$24,$a1
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref1:
	.db $f9,$85
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref2:
	.db $f9,$85
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref3:
	.db $f9,$85
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref4:
	.db $f9,$85
	.db $fd
	.dw .song0ch4loop
